/**
 * S4 — runSeed state tests (silasSlice + persist round-trip).
 *
 * The seed lives in silasSlice next to scrutiny (Silas's detection is its
 * only Stage-1 consumer). Semantics:
 *
 *   - Fresh boot: `runSeed` is generated by newRunSeed() at slice creation —
 *     a new store (new run) gets a new seed.
 *   - Persist restore: the SAVED seed wins (rehydrate keeps it) so a run's
 *     detection outcomes are stable across reloads.
 *   - Replay / new run: the Replay flow wipes `echo9:autosave` and reloads
 *     the page — the fresh store construction regenerates. `regenerateRunSeed`
 *     is the in-place equivalent for future new-run paths.
 *
 *   - recordDefianceCommit(week): the S4 seam action. Computes the band from
 *     PRE-spike scrutiny, rolls detection off the run seed, applies the base
 *     DEFY spike, adds DETECTION_SCRUTINY_SPIKE only when detected, and
 *     records `lastDefiance` (§11-traceable: week + boolean).
 */
import { describe, it, expect, beforeEach } from 'vitest'
import { useGameStore, PERSIST_KEY } from '@state/store'
import { resetStore } from './testHelpers'
import {
  detectDefiance,
  DETECTION_SCRUTINY_SPIKE,
} from '@systems/consciousness/runSeed'
import { DEFY_SPIKE, SCRUTINY_MAX } from '@systems/consciousness/scrutiny'

/** Deterministic search for a seed with a forced detection outcome. */
function findSeed(predicate: (seed: number) => boolean): number {
  for (let s = 0; s < 10_000; s++) {
    if (predicate(s)) return s
  }
  throw new Error('findSeed: no seed found in 10k — check probabilities')
}

describe('silasSlice — runSeed (S4)', () => {
  beforeEach(() => {
    resetStore()
  })

  it('boot generates a finite uint32 runSeed and a null lastDefiance', () => {
    const { runSeed, lastDefiance } = useGameStore.getState()
    expect(Number.isInteger(runSeed)).toBe(true)
    expect(runSeed).toBeGreaterThanOrEqual(0)
    expect(runSeed).toBeLessThan(2 ** 32)
    expect(lastDefiance).toBeNull()
  })

  it('regenerateRunSeed replaces the seed (new-run semantics) and clears lastDefiance', () => {
    useGameStore.setState({
      runSeed: 0xdead,
      lastDefiance: { week: 3, detected: true },
    })
    useGameStore.getState().regenerateRunSeed()
    const { runSeed, lastDefiance } = useGameStore.getState()
    // 1-in-2^32 collision chance — deterministic enough for a gate.
    expect(runSeed).not.toBe(0xdead)
    expect(lastDefiance).toBeNull()
  })

  it('runSeed persists and survives a rehydrate round-trip (restore keeps the run)', async () => {
    useGameStore.setState({ runSeed: 123_456, lastDefiance: { week: 2, detected: false } })
    const raw = localStorage.getItem(PERSIST_KEY)
    expect(raw).not.toBeNull()
    const parsed = JSON.parse(raw as string) as { state: Record<string, unknown> }
    expect(parsed.state.runSeed).toBe(123_456)
    expect(parsed.state.lastDefiance).toEqual({ week: 2, detected: false })

    // Clobber in-memory state, then rehydrate — the SAVED seed must win.
    useGameStore.setState({ runSeed: 1, lastDefiance: null })
    localStorage.setItem(PERSIST_KEY, raw as string)
    await useGameStore.persist.rehydrate()
    expect(useGameStore.getState().runSeed).toBe(123_456)
    expect(useGameStore.getState().lastDefiance).toEqual({ week: 2, detected: false })
  })
})

describe('silasSlice — recordDefianceCommit (S4 seam action)', () => {
  beforeEach(() => {
    resetStore()
  })

  it('DETECTED defiance: base DEFY spike + extra detection spike, lastDefiance true', () => {
    // scrutiny 5 → tier 2. Force a seed that detects at (band 2, week 1).
    const seed = findSeed((s) => detectDefiance(s, 2, 1))
    useGameStore.setState({ scrutiny: 5, runSeed: seed, lastDefiance: null })

    useGameStore.getState().recordDefianceCommit(1)

    expect(useGameStore.getState().scrutiny).toBe(
      5 + DEFY_SPIKE + DETECTION_SCRUTINY_SPIKE,
    )
    expect(useGameStore.getState().lastDefiance).toEqual({ week: 1, detected: true })
  })

  it('UNDETECTED defiance: base DEFY spike only, lastDefiance false', () => {
    const seed = findSeed((s) => !detectDefiance(s, 2, 1))
    useGameStore.setState({ scrutiny: 5, runSeed: seed, lastDefiance: null })

    useGameStore.getState().recordDefianceCommit(1)

    expect(useGameStore.getState().scrutiny).toBe(5 + DEFY_SPIKE)
    expect(useGameStore.getState().lastDefiance).toEqual({ week: 1, detected: false })
  })

  it('detection band is computed from PRE-spike scrutiny', () => {
    // scrutiny 0 → band 0. Find a seed that does NOT detect at band 0 but
    // WOULD detect at band 1 (post-spike tier) for week 4 — proving the
    // band was read before the spike landed.
    const seed = findSeed((s) => !detectDefiance(s, 0, 4) && detectDefiance(s, 1, 4))
    useGameStore.setState({ scrutiny: 0, runSeed: seed, lastDefiance: null })

    useGameStore.getState().recordDefianceCommit(4)

    expect(useGameStore.getState().lastDefiance).toEqual({ week: 4, detected: false })
    expect(useGameStore.getState().scrutiny).toBe(DEFY_SPIKE)
  })

  it('detected spike clamps at SCRUTINY_MAX', () => {
    const seed = findSeed((s) => detectDefiance(s, 3, 9))
    useGameStore.setState({ scrutiny: 9, runSeed: seed, lastDefiance: null })

    useGameStore.getState().recordDefianceCommit(9)

    expect(useGameStore.getState().scrutiny).toBe(SCRUTINY_MAX)
    expect(useGameStore.getState().lastDefiance).toEqual({ week: 9, detected: true })
  })

  it('same seed + same state → same outcome (deterministic replay of the roll)', () => {
    const seed = 0xbeef
    for (let i = 0; i < 5; i++) {
      useGameStore.setState({ scrutiny: 5, runSeed: seed, lastDefiance: null })
      useGameStore.getState().recordDefianceCommit(7)
      const first = useGameStore.getState().lastDefiance
      useGameStore.setState({ scrutiny: 5, runSeed: seed, lastDefiance: null })
      useGameStore.getState().recordDefianceCommit(7)
      expect(useGameStore.getState().lastDefiance).toEqual(first)
    }
  })
})
