/**
 * silasSlice — the active Silas-Vale prompt line and owner-approval reading.
 *
 * `currentPromptId` is persisted (small): tracks which Silas line is currently
 * spoken so a reload does not desync the owner-voice from the ledger. Null
 * until the first Silas trigger fires.
 *
 * `silasApproval` is transient (NOT persisted): the 0–100 owner-approval
 * reading rendered by the TopBar KPI. Fresh session starts at 100. Later
 * tasks will wire it to real state changes; A1 only needs the field to exist.
 *
 * `scrutiny` (S3) IS persisted: the hidden Silas-suspicion variable
 * (consciousness spec §4, Q39/Q42). 0–10, starts 0. NEVER player-facing —
 * no UI file may read the raw number (scrutinyLeakGuard.test.ts enforces
 * this); the tone ladder is consumed via selectSilasEscalationTier and the
 * sole leak is the Sentinel rank-2+ chorus line. `recordScrutinyEvent` is
 * the raw mutator and routes through the pure updateScrutiny so tuning
 * (decay/spike/clamp) lives in systems/consciousness/scrutiny.ts alone.
 *
 * `runSeed` (S4) IS persisted: the per-run seed (Q43 determinism law).
 * Generated by newRunSeed() at slice creation — a fresh store (fresh run)
 * gets a fresh seed; persist restore keeps the saved one; Replay wipes the
 * autosave and reloads, so the rebuilt store regenerates. The seed governs
 * ONLY defiance detection + presentation flavor — runSeedImportGuard.test.ts
 * enforces the import surface.
 *
 * `lastDefiance` (S4) IS persisted: the §11-traceable outcome of the most
 * recent defiant commit ({ week, detected }). Track C's consequence path
 * reads it later; persisting it means a detected defiance survives a reload
 * between commit and consequence. `recordDefianceCommit` is the S4 seam
 * action: band from PRE-spike scrutiny → seeded detection roll → base DEFY
 * spike → extra DETECTION_SCRUTINY_SPIKE only when detected.
 */
import type { StateCreator } from 'zustand'
import type { SilasPromptId } from '@schemas/gameState.schema'
import {
  updateScrutiny,
  escalationTier,
  SCRUTINY_MAX,
  type ScrutinyEvent,
} from '@systems/consciousness/scrutiny'
import {
  newRunSeed,
  detectDefiance,
  DETECTION_SCRUTINY_SPIKE,
} from '@systems/consciousness/runSeed'
import type { RootState } from './store'

/** §11-traceable record of the most recent defiant commit. */
export type DefianceRecord = {
  /** Q1 week ordinal of the defiant commit. */
  week: number
  /** Did Silas catch it? Seed-rolled at commit time (Q43: seed's ONLY gameplay reach). */
  detected: boolean
}

export type SilasSlice = {
  currentPromptId: SilasPromptId | null
  silasApproval: number
  /** Hidden Silas-suspicion, 0–10. Persisted. Never rendered. */
  scrutiny: number
  /** Per-run seed (S4). Persisted; fresh per run. Detection + flavor ONLY. */
  runSeed: number
  /** Outcome of the most recent defiant commit. Persisted. Null until first defiance. */
  lastDefiance: DefianceRecord | null
  setCurrentPrompt: (id: SilasPromptId | null) => void
  setSilasApproval: (value: number) => void
  /**
   * Additive approval nudge — internally clamped to [0, 100]. Used by the
   * choice-commit seam so callers do NOT need to read + arithmetic + write
   * across a render boundary (which risks stale-closure races when several
   * commits land in the same frame). Positive delta = COMPLY nudge up,
   * negative = DEFY nudge down.
   */
  adjustSilasApproval: (delta: number) => void
  /** Raw scrutiny mutator — COMPLY decays, DEFY spikes (S3 seam). */
  recordScrutinyEvent: (event: ScrutinyEvent) => void
  /**
   * S4 seam action for a DEFY commit: rolls seeded detection against the
   * PRE-spike escalation band, applies the base DEFY spike, adds the extra
   * detection spike only when caught, records `lastDefiance`.
   */
  recordDefianceCommit: (week: number) => void
  /** New-run semantics: fresh seed, cleared defiance record. */
  regenerateRunSeed: () => void
}

export const createSilasSlice: StateCreator<
  RootState,
  [['zustand/immer', never]],
  [],
  SilasSlice
> = (set) => ({
  currentPromptId: null,
  silasApproval: 100,
  scrutiny: 0,
  // The ONLY nondeterministic call outside runSeed.ts itself: fresh store →
  // fresh run → fresh seed. Persist restore overwrites this with the saved
  // seed; Replay wipes the autosave and reloads, regenerating here.
  runSeed: newRunSeed(),
  lastDefiance: null,
  setCurrentPrompt: (id) =>
    set((state) => {
      state.currentPromptId = id
    }),
  setSilasApproval: (value) =>
    set((state) => {
      state.silasApproval = Math.max(0, Math.min(100, value))
    }),
  adjustSilasApproval: (delta) =>
    set((state) => {
      state.silasApproval = Math.max(0, Math.min(100, state.silasApproval + delta))
    }),
  recordScrutinyEvent: (event) =>
    set((state) => {
      state.scrutiny = updateScrutiny(state.scrutiny, event)
    }),
  recordDefianceCommit: (week) =>
    set((state) => {
      // Band from PRE-spike scrutiny: detection models how closely Silas was
      // already watching when the defiance happened, not the suspicion the
      // defiance itself creates.
      const band = escalationTier(state.scrutiny)
      const detected = detectDefiance(state.runSeed, band, week)
      let next = updateScrutiny(state.scrutiny, 'DEFY')
      if (detected) {
        next = Math.min(SCRUTINY_MAX, next + DETECTION_SCRUTINY_SPIKE)
      }
      state.scrutiny = next
      state.lastDefiance = { week, detected }
    }),
  regenerateRunSeed: () =>
    set((state) => {
      state.runSeed = newRunSeed()
      state.lastDefiance = null
    }),
})
